### ISSUE TITLE
deleting evetns -> quit -> exception

### ISSUE THREAD

**Issue by petr-fischer** [pimutils/khal#734] opened 2017-10-26 14:07 UTC
Hello, in interactive mode, when I delete twi events, they are showed with "D" prefix and then, when I quit khal (from interactive mode), this exception occurs:
```
Traceback (most recent call last):
  File "/home/pf/.local/lib/python3.6/site-packages/khal/ui/__init__.py", line 1300, in start_pane
    loop.run()
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 509, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/home/pf/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 555, in unhandled_input
    return self._unhandled_input(input)
  File "/home/pf/.local/lib/python3.6/site-packages/khal/ui/base.py", line 162, in on_key_press
    self.backtrack()
  File "/home/pf/.local/lib/python3.6/site-packages/khal/ui/base.py", line 147, in backtrack
    cb(data)
  File "/home/pf/.local/lib/python3.6/site-packages/khal/ui/__init__.py", line 1095, in cleanup
    self.collection.delete(href, etag, account)
  File "/home/pf/.local/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 216, in delete
    self._storages[calendar].delete(href, etag)
  File "/home/pf/.local/lib/python3.6/site-packages/khal/khalendar/vdir.py", line 261, in delete
    raise WrongEtagError(etag, actual_etag)
khal.khalendar.vdir.WrongEtagError: [Errno 1509023350231546112.000000000] 1509023358481625088.000000000
```

**Comment by geier** [comment] 2017-11-08 10:29
This looks like the file on disk changed between opening ikhal and closing it. Can you reproduce this, or was this a one time occurrence? 

Anyway, a much nicer error message is really needed.

**Comment by petr-fischer** [comment] 2017-11-08 11:02
I tested this issue several times before - but today, everything with deleting events is OK (no exceptions).
When I delete event, this is a "tag for deletion only" action, right? Events for deletion are finally deleted after khal exits from interactive mode, right? Is there a way to "commit" actual deletions? Thanks!

**Comment by geier** [comment] 2017-11-08 14:18
No, that isn't possible at the moment (see #536).

**Closed** 2017-11-08 14:28 UTC
Labels: type: bug
