### ISSUE TITLE
Early log entries do not get printed

### ISSUE THREAD

**Issue by geier** [pimutils/khal#688] opened 2017-07-24 15:57 UTC
Anything logged before we actually set up logging gets disregarded, I tried to fix some of it by [moving logging of settings to a later point](5a673c1e3cf531b88a4678c6aa040732d0655593), but I broke more stuff with it and therefore reverted it. 

Parsing of the configuration file happens before, the log messages generated there do not get printed, also the version number doesn't get printed and neither does the current settings (with -v DEBUG).

**Comment by geier** [comment] 2017-07-24 16:07
@hobarrera @untitaker Is this a general limitation of click-log or can this be worked around?

**Comment by hobarrera** [comment] 2017-07-24 16:48
Due to how `click_log` is designed, anything previous to the `click` command will be run without the logger set up (in other words, anything before [this line](https://github.com/pimutils/khal/blob/90864f2/khal/cli.py#L240).

I do *think* that swapping the order of [these two lines](https://github.com/pimutils/khal/blob/90864f2/khal/cli.py#L238-L240) might have `global_options` (and settings loading) logged properly (since decorators actually end up running bottom-to-top.

**Comment by untitaker** [comment] 2017-07-24 16:51
This won't work. The problem is that the config option is defined as eager. This can be fixed in click-log I think, but not sure. 

On 24 July 2017 18:48:29 GMT+02:00, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Due to how `click_log` is designed, anything previous to the `click`
>command will be run without the logger set up (in other words, anything
>before [this
>line](https://github.com/pimutils/khal/blob/90864f2/khal/cli.py#L240).
>
>I do *think* that swapping the order of [these two
>lines](https://github.com/pimutils/khal/blob/90864f2/khal/cli.py#L238-L240)
>might have `global_options` (and settings loading) logged properly
>(since decorators actually end up running bottom-to-top.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/688#issuecomment-317483269

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment] 2017-07-24 17:13
Oh, good catch. I wonder if `click_log` could have some flag to optionally make it eager (which, AFAIK, wouldn't hurt in this case).

**Comment by untitaker** [comment] 2017-07-24 18:10
This turns out to be quite complex, and will require a new (non-breaking) `click-log` release that exposes a new API for this.

**Comment by untitaker** [comment] 2017-07-24 19:19
@geier https://github.com/click-contrib/click-log/commit/b725bcdcb8b0186128ab8c727c43aa5a805443a7 should work. Please tell me if the docs are sufficient.

**Comment by geier** [comment] 2017-07-25 13:50
@untitaker thank you, works as advertised.

**Comment by geier** [comment] 2017-07-25 15:01
at isn't that simple after all, the new test (see branch pre_record) works with when run alone ( pytest -k debug tests/cli_test.py ), but not together with the other tests. I'll investigate.

**Comment by untitaker** [comment] 2017-07-25 15:31
That makes sense, since the prerecording is global state. I'll have to think about this. Perhaps this is not a good solution after all.

On 25 July 2017 17:15:21 GMT+02:00, Christian Geier <notifications@github.com> wrote:
>at isn't that simple after all, the new test (see branch pre_record)
>works with when run alone ( pytest -k debug tests/cli_test.py ), but
>not together with the other tests. I'll investigate.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/688#issuecomment-317766303

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment] 2017-07-27 20:10
Could you update click-log from master and try again?

**Comment by untitaker** [comment] 2017-07-27 20:39
Ok, I now broke the API of click-log. Please remove the `@click_log.init`-line, add `click_log.basic_config("khal")` at module level and also define your verbosity option before you define the config option.

If that works for you I will release a new version.

**Closed** 2017-08-28 19:34 UTC
Labels: in progress, type: bug
