### ISSUE TITLE
iOS contacts can't be parsed (for their birthdays)

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#475] opened 2016-08-17 03:54 UTC
Looks like something goes wrong attempting to parse their photo metadata. This is a non-standard field. Shouldn't we accept just about anything that doesn't break the basic format here?

```
Unknown exception happened.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 230, in from_ical
    key, val = q_split(param, '=')
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 336, in parts
    strict=self.strict)
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 255, in from_ical
    % (param, exc))
ValueError: 'X-ABCROP-RECTANGLE=ABClipRect_1&0&38&442&442&aRlkb8jkglNEEeAl7S7liw==' is not a valid parameter string: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 293, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/lib/python3.5/site-packages/khal/khalendar/backend.py", line 276, in update_birthday
    ical = icalendar.Event.from_ical(vevent)
  File "/usr/lib/python3.5/site-packages/icalendar/cal.py", line 328, in from_ical
    name, params, vals = line.parts()
  File "/usr/lib/python3.5/site-packages/icalendar/parser.py", line 346, in parts
    % (self, exc)
ValueError: Content line could not be parsed into parts: 'PHOTO;ENCODING=b;TYPE=JPEG;X-ABCROP-RECTANGLE=ABClipRect_1&0&38&442&442&aRlkb8jkglNEEeAl7S7liw==:/9j/4AAQSkZJRgABAQAASABIAAD/4SjzRXhpZgAATU0AKgAAAAgABgESAAM

[[ TRIMMED ~120k characters of base64 data]]

yv9k+5XRhafJMSqcnvnSJDAlmny/O/wB+rGn/AOjfPu/26r6U/wBsWLfUmrzeSyJurpq/HyHVTxPuQJL7xC7q8cf3/uVj6e928r/N9+qmnw/bLry93367uwS1tv3aNvdKKnue+GFq++f/2Q==': 'X-ABCROP-RECTANGLE=ABClipRect_1&0&38&442&442&aRlkb8jkglNEEeAl7S7liw==' is not a valid parameter string: too many values to unpack (expected 2)
warning: This event will not be available in khal.
```

**Comment by geier** [comment] 2016-08-17 09:47
I agree, we should accept this event, ignore the invalid line and print a warning instead. The problem is, this is out of our hands, this really is an [https://github.com/collective/icalendar](icalendar) issue.

**Comment by geier** [comment] 2016-09-07 23:04
I believe this is basically the same problem as #467

**Comment by hobarrera** [comment] 2016-09-07 23:13
#467 is about events, this is about contacts, but yes, it's almost the same issue (I'm not sure if the underlying code is the same or not. It's also worth noting that there's not potential data loss here).

**Comment by geier** [comment] 2017-04-20 17:10
This should finally be fixed within icalendar, but the patch hasn't made it into a release yet. You should be able to fix this issue with ``pip install --upgrade git+https://github.com/collective/icalendar.git``.

**Comment by geier** [comment] 2017-05-11 15:45
As a new version of icalendar was released yesterday, I'll close this bug now. Please reopen if you stumble upon it with icalendar > 3.11.4.

**Closed by geier** 2017-05-11 15:45 UTC
Labels: type: bug, upstream
