### ISSUE TITLE
Question about coloring

### ISSUE THREAD

**Issue by cpfaff** [pimutils/khal#1182] opened 2022-09-03 08:46 UTC
I was trying to get as close to gruvbox coloring as possible. So I started by copying the dark theme in ui/colors.py first and adapted everything to my needs. This is already quite nice. However I thought I could do better. I just saw that it might also be possible to use hex colors. But when I specify one of these and call ikhal I get spit out the message that I require more colors than are specified:

```
Traceback (most recent call last):
  File "/usr/bin/ikhal", line 5, in <module>
    main_ikhal()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/khal/cli.py", line 498, in interactive_cli
    controllers.interactive(
  File "/usr/lib/python3.10/site-packages/khal/controllers.py", line 575, in interactive
    ui.start_pane(
  File "/usr/lib/python3.10/site-packages/khal/ui/__init__.py", line 1329, in start_pane
    loop = urwid.MainLoop(
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 118, in __init__
    screen.register_palette(palette)
  File "/usr/lib/python3.10/site-packages/urwid/display_common.py", line 856, in register_palette
    self.register_palette_entry(*item)
  File "/usr/lib/python3.10/site-packages/urwid/display_common.py", line 923, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)
  File "/usr/lib/python3.10/site-packages/urwid/display_common.py", line 540, in __init__
    raise AttrSpecError(('foreground/background (%s/%s) require ' +
urwid.display_common.AttrSpecError: foreground/background ('#00FF00'/'#00FF00') require more colors than have been specified (16).
```

It seems to be stuck to 16 colors. I do not get this as my suckless terminal actually supports true colors. Do I need to make some more adaptions to khal code to pick that up correctly? And how would I do it?

![screenshot-2022-09-03:10:46](https://user-images.githubusercontent.com/1726483/188263313-02bda1e4-96c2-4842-9cad-544ed28338f2.png)

EDIT:

```
* khal --version
khal, version 0.10.5
```

**Comment by WhyNotHugo** [comment] 2022-09-03 09:01
Can you share your code/changes?

Nothing obvious comes to mind, but the issue here is in urwid and what values are being passed to it. The issue is not due to terminal support.

**Comment by cpfaff** [comment] 2022-09-03 09:09
Sure I can share it. Here you go. I only edited the `colors.py` adding another array with colors for gruvbox. 

```
gruvbox = [
    ("header", "white", "black"),
    ("footer", "white", "black"),
    ("today", "#00FF00", "#00FF00"),
    ("today focus", "black", "yellow"),
    ("date header", "white", "black"),
    ("date header focused", "yellow", "black"),
    ("date header selected", "yellow", "black"),
    ("reveal focus", "yellow", "black"),
    ("dayname", "light gray", ""),
    ("monthname", "light gray", ""),
    ("edit", "yellow", "black"),
    ("edit focused", "yellow", "black"),
    ("alert", "white", "dark red"),
    ("mark", "white", "dark green"),
]
```

I also set this new theme to be picked up in `khal.spec`. I also set it default here just for now altough this could be done by configuration later.

```
theme = option('dark', 'light', 'gruvbox', default='gruvbox')
```

**Comment by cpfaff** [comment] 2022-09-03 09:10
Here in that case you see where I just tried to use hex color codes. That breaks it. Before that I had there "black" and "yellow" named colors.

**Comment by cpfaff** [comment] 2022-09-03 11:18
Intresting. Just tried using hex colors in the config for the calenders. There it works.

**Comment by cpfaff** [comment] 2022-09-03 15:09
I am investigating. Here it breaks when passing the palette to the urwid main loop. 

```
    palette = _add_calendar_colors(
        getattr(colors, pane._conf['view']['theme']), pane.collection)
```

I also saw that there is a fuction that generates a urwid compatible color entry which is named `_urwid_palette_entry`. That one is also used adding the calendar colors to the palette. Thus it is called from `_add_calendar_colors`. I see there conditional treatment for hex colors and does the right thing for hex values coming from the configuration. The color theme however, as far as I can see is passed to the pane without further treatment? That makes it break.

**Comment by WhyNotHugo** [comment] 2022-09-03 15:42
So the built-in themes are in a different format than those provided via a config file, and because of that they're also fed differently to urwid. From what I see in your research here, the built-in ones don't support hex colours.

I wonder if built-in themes should share the same format as user-defined ones. E.g.: Just put them into `ini` files and thread them the same. When a user wants a custom colour, they just write a custom `ini` file too and point their config file to it.

This would remove the "two separate formats" flow and code. Potentially, code can be made simpler, fix this bug **and** also make is easy for users to share colour themes or even upstream them into `contrib/` (since each theme is just an file).

_(`ini` is just an example here, could be whatever fits best really)_

@geier Thoughts?

**Comment by geier** [comment] 2022-10-29 12:49
yeah, the color scheme code should be completely re-done. Defining a complete color scheme in the config should be allowed as well. (Or perhaps we should allow plugins.)

**Comment by geier** [comment] 2023-06-17 16:23
If I see this correctly, the entries need to be in the form `(name, foreground_16_colors, background_16_colors, monochrome_settings, foreground_unilimited_colors, background_unlimited_colors)`, see the [urwid documentation](https://urwid.org/reference/display_modules.html#urwid.BaseScreen.register_palette_entry). 

Seems to work 
<img width="815" alt="image" src="https://github.com/pimutils/khal/assets/275330/fc10e3e4-37f1-4390-98ef-3b7a9d1b5fe9">
<img width="868" alt="image" src="https://github.com/pimutils/khal/assets/275330/6000c37a-bb98-4e9d-9c36-79aed4e4081b">
(those color names are from the gruvbox site).

While playing a bit with those colors I noticed how many elements currently do not have a attribute element (e.g. most buttons), so we need some work there as well.

**Comment by geier** [comment] 2023-06-23 21:51
if anyone is interested in testing defining colors in the config file, please see https://github.com/pimutils/khal/pull/1279

**Comment by geier** [comment] 2023-06-23 22:08
I'll close this for now, please re-open this or another one if any questions are still open.

**Closed by geier** 2023-06-23 22:08 UTC
Labels: type: question
