### ISSUE TITLE
[FreeBSD] not building doc.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [pimutils/khal#883] opened 2019-09-19 15:06 UTC
Hello,

I am having some problems to build docs in here. :-]

https://github.com/pimutils/khal/blob/c4f5cd7248abb08a65dbb337bfe5e7e57e2e4a4d/doc/Makefile#L10-L13

These lines die with:

```
make: "/home/rigoletto/Dev/FreeBSD/ports/deskutils/py-khal/work-py36/khal-0.10.1/doc/Makefile" line 11: Missing dependency operator
make: Unknown modifier '/'
make: "/home/rigoletto/Dev/FreeBSD/ports/deskutils/py-khal/work-py36/khal-0.10.1/doc/Makefile" line 12: Need an operator
make: "/home/rigoletto/Dev/FreeBSD/ports/deskutils/py-khal/work-py36/khal-0.10.1/doc/Makefile" line 13: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /home/rigoletto/Dev/FreeBSD/ports/deskutils/py-khal/work-py36/khal-0.10.1/doc
```

Removing them I can go on but can't really build anything (e.g.):

```
# Sphinx version: 1.6.5
# Python version: 3.6.9 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python3.6/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python3.6/site-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 15, in <module>
ModuleNotFoundError: No module named 'khal'
```

Thank you.

**Comment by geier** [comment] 2019-09-23 10:48
You probably need `gmake` on FreeBSD and you need to have khal already installed to have the documentation build.

**Comment by ephase** [comment] 2019-09-23 12:02
Hi,
This is it, you need to install `gmake` and `khal` to build it, i troied today on a jail and it work : 
```
pkg install py36-sphinx py36-sphinxcontrib-newsfeed git gmake py36-khal
[...]
git clone https://github.com/pimutils/khal/
[...]
cd khal/doc/
gmake
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.5
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 40 source files that are out of date
updating environment: 40 added, 0 changed, 0 removed
reading sources... [100%] usage                                                                                                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... /root/khal/doc/source/man.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] usage                                                                                                                                
/root/khal/doc/source/configure.rst:17: WARNING: unknown option: -c
path/to/config
/root/khal/doc/source/usage.rst:53: WARNING: unknown option: --color
/root/khal/doc/source/usage.rst:53: WARNING: unknown option: --color
/root/khal/doc/source/usage.rst:395: WARNING: unknown option: --interactive
generating indices... genindex
writing additional pages... search
copying images... [100%] images/rss.png                                                                                                                       
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 5 warnings.

Build finished. The HTML pages are in build/html.
```
I have some warning but files are here.

**Comment by rigoletto-freebsd** [comment] 2019-09-23 12:30
I will have a look ASAP.

Thank you.

**Comment by rigoletto-freebsd** [comment] 2019-09-23 21:41
Just now I see this is marked as bug, and then I will re-open it. :-)

Btw, for now I will leave khal building without documentation because otherwise I would need to create a separate port for documentation (overkill) or use the post-install (ugly).

Thank you.

**Comment by geier** [comment] 2020-10-02 18:39
I only marked this as a bug because the cause wasn't clear. Is there a way to help you make the port building cleaner?

I'll close this issue now, but feel free to open a new issue with any enhancement proposals for helping maintainers.

**Closed by geier** 2020-10-02 18:39 UTC
Labels: type: bug, type: documentation
