### ISSUE TITLE
Test failures for 0.8.2

### ISSUE THREAD

**Issue by lfam** [pimutils/khal#422] opened 2016-05-26 19:15 UTC
I'm trying to build khal 0.8.2 for Guix, but I'm getting some test failures, as shown in the attached build log.

On #pimutils, it was suggested to increase the sleep times in khalendar_test.py. Sleeping for 1 second,   TestCalendar.test_db_needs_update did pass, but the other failures remained.

Versions of some dependencies and other potentially useful information:
linux-4.5.0
ext4 filesystem
x86_64 architecture
python-icalendar-3.10
python-dateutil-2.5.3
pytest-2.7.3
freezegun-0.3.7

Please let me know how I can help debug this.

Also, if these test failures indicate a problem with the tests themselves, rather than with khal, please let me know so I can disable them and update our package.

[khal-log.txt](https://github.com/pimutils/khal/files/285124/khal-log.txt)

**Comment by geier** [comment] 2016-05-28 06:36
I believe the failure of `aux/test_repeat()` is a bit different than the others, but I cannot reproduce it locally. If anyone can, can you paste the output of `pytest -v`? (or perhaps with some more added `v`s).

**Comment by lfam** [comment] 2016-05-29 19:28
Here is the output of `py.test --verbose tests`, from within the Guix build environment. What's weird is that the only failing test is 'tests/aux_test.py', even though I haven't changed anything besides invoking pytest with `--verbose`.

```
starting phase `check'
============================= test session starts ==============================
platform linux -- Python 3.4.3 -- py-1.4.31 -- pytest-2.7.3 -- /gnu/store/s7dh9x5f6vl4ww3vyjh831mh828jfr17-python-wrapper-3.4.3/bin/python
rootdir: /tmp/guix-build-khal-0.8.2.drv-0/khal-0.8.2, inifile: 
collecting ... collected 177 items

tests/aux_test.py::test_normalize_component PASSED
tests/aux_test.py::TestGuessDatetimefstr::test_today PASSED
tests/aux_test.py::TestGuessDatetimefstr::test_tomorrow PASSED
tests/aux_test.py::TestGuessDatetimefstr::test_time_tomorrow PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_single PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_negative PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_multi PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_multi_nospace PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_garbage PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_moregarbage PASSED
tests/aux_test.py::TestGuessTimedeltafstr::test_same PASSED
tests/aux_test.py::test_construct_event_format_de PASSED
tests/aux_test.py::test_construct_event_format_us PASSED
tests/aux_test.py::test_construct_event_format_de_complexer PASSED
tests/aux_test.py::test_leap_year PASSED
tests/aux_test.py::test_description PASSED
tests/aux_test.py::test_repeat FAILED
tests/aux_test.py::test_alarm PASSED
tests/aux_test.py::test_description_and_location PASSED
tests/aux_test.py::TestIcsFromList::test_ics_from_list PASSED
tests/aux_test.py::TestIcsFromList::test_ics_from_list_random_uid PASSED
tests/backend_test.py::test_new_db_version PASSED
tests/backend_test.py::test_event_rrule_recurrence_id PASSED
tests/backend_test.py::test_event_different_timezones PASSED
tests/backend_test.py::test_event_rrule_recurrence_id_invalid_tzid PASSED
tests/backend_test.py::test_event_rrule_recurrence_id_reverse PASSED
tests/backend_test.py::test_event_rrule_recurrence_id_update_with_exclude PASSED
tests/backend_test.py::test_no_valid_timezone PASSED
tests/backend_test.py::test_event_delete PASSED
tests/backend_test.py::test_this_and_prior PASSED
tests/backend_test.py::test_event_rrule_this_and_future PASSED
tests/backend_test.py::test_event_rrule_this_and_future_multi_day_shift PASSED
tests/backend_test.py::test_event_rrule_this_and_future_allday PASSED
tests/backend_test.py::test_event_rrule_this_and_future_allday_prior PASSED
tests/backend_test.py::test_event_rrule_multi_this_and_future_allday PASSED
tests/backend_test.py::test_calc_shift_deltas PASSED
tests/backend_test.py::test_two_calendars_same_uid PASSED
tests/backend_test.py::test_update_one_should_not_affect_others PASSED
tests/backend_test.py::test_zuluv_events PASSED
tests/backend_test.py::test_no_dtend PASSED
tests/backend_test.py::test_check_support PASSED
tests/backend_test.py::test_birthdays PASSED
tests/backend_test.py::test_birthdays_no_year PASSED
tests/backend_test.py::test_birthdays_no_fn PASSED
tests/backend_test.py::test_birthday_does_not_parse PASSED
tests/backend_test.py::test_vcard_two_birthdays PASSED
tests/cal_display_test.py::test_getweeknumber PASSED
tests/cal_display_test.py::test_str_week PASSED
tests/cal_display_test.py::test_vertical_month PASSED
tests/cal_display_test.py::test_vertical_month_unicode PASSED
tests/cal_display_test.py::test_vertical_month_unicode_weekdeays xfail
tests/cal_display_test.py::test_vertical_month_unicode_weekdeays_gr PASSED
tests/cli_test.py::test_direct_modification PASSED
tests/cli_test.py::test_simple PASSED
tests/cli_test.py::test_simple_color PASSED
tests/cli_test.py::test_days PASSED
tests/cli_test.py::test_showalldays PASSED
tests/cli_test.py::test_calendar xfail
tests/cli_test.py::test_default_command_empty PASSED
tests/cli_test.py::test_default_command_nonempty PASSED
tests/cli_test.py::test_invalid_calendar PASSED
tests/cli_test.py::test_attach_calendar PASSED
tests/cli_test.py::test_no_vevent[] PASSED
tests/cli_test.py::test_no_vevent[BEGIN:VCALENDAR
BEGIN:VTODO
END:VTODO
END:VCALENDAR
] PASSED
tests/cli_test.py::test_printformats PASSED
tests/cli_test.py::test_repeating PASSED
tests/cli_test.py::test_at PASSED
tests/cli_test.py::test_search PASSED
tests/cli_test.py::test_interactive_command PASSED
tests/cli_test.py::test_color_option PASSED
tests/cli_test.py::test_configure_command PASSED
tests/controller_test.py::TestGetAgenda::test_new_event PASSED
tests/controller_test.py::TestGetAgenda::test_empty_recurrence PASSED
tests/controller_test.py::TestImport::test_import PASSED
tests/controller_test.py::TestImport::test_mix_datetime_types PASSED
tests/event_test.py::test_no_initialization PASSED
tests/event_test.py::test_invalid_keyword_argument PASSED
tests/event_test.py::test_raw_dt PASSED
tests/event_test.py::test_update_simple PASSED
tests/event_test.py::test_raw_d PASSED
tests/event_test.py::test_update_sequence PASSED
tests/event_test.py::test_event_organizer PASSED
tests/event_test.py::test_transform_event PASSED
tests/event_test.py::test_update_event_d PASSED
tests/event_test.py::test_update_event_duration PASSED
tests/event_test.py::test_dt_two_tz PASSED
tests/event_test.py::test_event_dt_duration PASSED
tests/event_test.py::test_event_dt_floating PASSED
tests/event_test.py::test_event_dt_tz_missing PASSED
tests/event_test.py::test_event_dt_rr PASSED
tests/event_test.py::test_event_d_rr PASSED
tests/event_test.py::test_event_rd PASSED
tests/event_test.py::test_event_d_long PASSED
tests/event_test.py::test_event_dt_long PASSED
tests/event_test.py::test_event_no_dst PASSED
tests/event_test.py::test_event_raw_UTC PASSED
tests/event_test.py::test_dtend_equals_dtstart PASSED
tests/event_test.py::test_multi_uid PASSED
tests/event_test.py::test_recur PASSED
tests/event_test.py::test_type_inference PASSED
tests/event_test.py::test_duplicate_event PASSED
tests/event_test.py::test_remove_instance_from_rrule PASSED
tests/event_test.py::test_remove_instance_from_rdate PASSED
tests/event_test.py::test_remove_instance_from_two_rdate PASSED
tests/event_test.py::test_remove_instance_from_recuid PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dt PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dtb PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dttz PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dtf PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_d PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dtz PASSED
tests/khalendar_aux_test.py::TestExpand::test_expand_dtzb PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_dt PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_dtb PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_dttz PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_dtf PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_d PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_dtr_exdatez PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_rrule_exdate_z PASSED
tests/khalendar_aux_test.py::TestExpandNoRR::test_expand_rrule_notz_until_z PASSED
tests/khalendar_aux_test.py::TestSpecial::test_count PASSED
tests/khalendar_aux_test.py::TestSpecial::test_until_notz PASSED
tests/khalendar_aux_test.py::TestSpecial::test_until_d_notz PASSED
tests/khalendar_aux_test.py::TestSpecial::test_latest_bug PASSED
tests/khalendar_aux_test.py::TestSpecial::test_another_problem PASSED
tests/khalendar_aux_test.py::TestSpecial::test_event_exdate_dt PASSED
tests/khalendar_aux_test.py::TestSpecial::test_event_exdates_dt PASSED
tests/khalendar_aux_test.py::TestSpecial::test_event_exdatesl_dt PASSED
tests/khalendar_aux_test.py::TestSpecial::test_event_dt_rrule_invalid_until PASSED
tests/khalendar_aux_test.py::TestSpecial::test_event_dt_rrule_invalid_until2 PASSED
tests/khalendar_aux_test.py::TestRDate::test_simple_rdate PASSED
tests/khalendar_aux_test.py::TestRDate::test_rrule_and_rdate PASSED
tests/khalendar_aux_test.py::TestRDate::test_rrule_past PASSED
tests/khalendar_aux_test.py::TestRDate::test_rdate_date PASSED
tests/khalendar_aux_test.py::TestSanitize::test_noend_date PASSED
tests/khalendar_aux_test.py::TestSanitize::test_noend_datetime PASSED
tests/khalendar_aux_test.py::TestSanitize::test_duration PASSED
tests/khalendar_test.py::TestCalendar::test_create PASSED
tests/khalendar_test.py::TestCalendar::test_new_event PASSED
tests/khalendar_test.py::TestCalendar::test_sanity PASSED
tests/khalendar_test.py::TestCalendar::test_db_needs_update PASSED
tests/khalendar_test.py::TestVdirsyncerCompat::test_list PASSED
tests/khalendar_test.py::TestCollection::test_default_calendar PASSED
tests/khalendar_test.py::TestCollection::test_empty PASSED
tests/khalendar_test.py::TestCollection::test_insert PASSED
tests/khalendar_test.py::TestCollection::test_insert_d PASSED
tests/khalendar_test.py::TestCollection::test_insert_d_no_value PASSED
tests/khalendar_test.py::TestCollection::test_get PASSED
tests/khalendar_test.py::TestCollection::test_change PASSED
tests/khalendar_test.py::TestCollection::test_update_event PASSED
tests/khalendar_test.py::TestCollection::test_newevent PASSED
tests/khalendar_test.py::TestCollection::test_modify_readonly_calendar PASSED
tests/khalendar_test.py::TestCollection::test_search PASSED
tests/khalendar_test.py::TestCollection::test_get_events_at PASSED
tests/khalendar_test.py::TestCollection::test_delete_two_events PASSED
tests/khalendar_test.py::TestDbCreation::test_create_db PASSED
tests/khalendar_test.py::TestDbCreation::test_failed_create_db PASSED
tests/khalendar_test.py::test_default_calendar PASSED
tests/khalendar_test.py::test_only_update_old_event PASSED
tests/settings_test.py::TestSettings::test_simple_config PASSED
tests/settings_test.py::TestSettings::test_nocalendars PASSED
tests/settings_test.py::TestSettings::test_small PASSED
tests/settings_test.py::TestSettings::test_old_config PASSED
tests/settings_test.py::TestSettings::test_extra_sections PASSED
tests/settings_test.py::test_discover PASSED
tests/settings_test.py::test_get_unique_name PASSED
tests/settings_test.py::test_config_checks PASSED
tests/terminal_test.py::test_colored PASSED
tests/terminal_test.py::TestMergeColumns::test_longer_right PASSED
tests/terminal_test.py::TestMergeColumns::test_longer_left PASSED
tests/vtimezone_test.py::test_berlin PASSED
tests/vtimezone_test.py::test_berlin_rdate PASSED
tests/vtimezone_test.py::test_bogota PASSED
tests/ui/test_calendarwidget.py::test_initial_focus_today PASSED
tests/ui/test_calendarwidget.py::test_set_focus_date PASSED
tests/ui/test_calendarwidget.py::test_set_focus_date_weekstart_6 PASSED
tests/ui/test_widgets.py::test_delete_last_word PASSED

=================================== FAILURES ===================================
_________________________________ test_repeat __________________________________

    def test_repeat():
        for data_list, vevent in test_set_repeat:
            with freeze_time('2014-02-16 12:00:00'):
                event = construct_event(data_list.split(),
                                        description='please describe the event',
                                        repeat='daily',
                                        until=['05.06.2015'],
                                        locale=locale_de)
>               assert _replace_uid(event).to_ical() == vevent
E               assert b'BEGIN:VEVEN...ND:VEVENT\r\n' == b'BEGIN:VEVENT...ND:VEVENT\r\n'
E                 Detailed information truncated, use "-vv" to show

tests/aux_test.py:323: AssertionError
=============== 1 failed, 174 passed, 2 xfailed in 38.05 seconds ===============
phase `check' failed after 43.1 seconds
```

**Comment by lfam** [comment] 2016-05-29 19:33
Also, another difference between today and  when I tried a few days ago is that now the system is more than fully loaded, whereas before there was no significant load.

And here is the extra information that is printed after replacing `--verbose` with `-vvv`:

```
=================================== FAILURES ===================================
_________________________________ test_repeat __________________________________

    def test_repeat():
        for data_list, vevent in test_set_repeat:
            with freeze_time('2014-02-16 12:00:00'):
                event = construct_event(data_list.split(),
                                        description='please describe the event',
                                        repeat='daily',
                                        until=['05.06.2015'],
                                        locale=locale_de)
>               assert _replace_uid(event).to_ical() == vevent
E               assert b'BEGIN:VEVEN...ND:VEVENT\r\n' == b'BEGIN:VEVENT...ND:VEVENT\r\n'
E                 At index 241 diff: 82 != 68
E                 Full diff:
E                 - b'BEGIN:VEVENT\r\nSUMMARY:\xc3\x84wes\xc3\xb6me Event\r\nDTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20140216T080000\r\nDTEND;TZID=Europe/Berlin;VALUE=DATE-TIME:20140216T090000\r\nDTSTAMP;VALUE=DATE-TIME:20140216T120000Z\r\nUID:E41JRQX2DB4P1AQZI86BAT7NHPBHPRIIHQKA\r\nRRULE:FREQ=DAILY;UNTIL=20150605T000000\r\nDESCRIPTION:please describe the event\r\nEND:VEVENT\r\n'
E                 ?                                                                                                                                                                                                                                                                            ------------------------------------------
E                 + b'BEGIN:VEVENT\r\nSUMMARY:\xc3\x84wes\xc3\xb6me Event\r\nDTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20140216T080000\r\nDTEND;TZID=Europe/Berlin;VALUE=DATE-TIME:20140216T090000\r\nDTSTAMP;VALUE=DATE-TIME:20140216T120000Z\r\nUID:E41JRQX2DB4P1AQZI86BAT7NHPBHPRIIHQKA\r\nDESCRIPTION:please describe the event\r\nRRULE:FREQ=DAILY;UNTIL=20150605T000000\r\nEND:VEVENT\r\n'
E                 ?                                                                                                                                                                                                                                                                                                                     ++++++++++++++++++++++++++++++++++++++++++

tests/aux_test.py:323: AssertionError
=============== 1 failed, 174 passed, 2 xfailed in 42.35 seconds ===============
phase `check' failed after 46.0 seconds
```

**Comment by geier** [comment] 2016-06-01 21:50
Test repeat is fixed in master, this started to fail because of dateutil's latest release.

**Comment by youngmoney** [comment] 2016-07-06 06:59
should we close this as it is fixed in master?

**Closed** 2016-07-06 19:22 UTC
Labels: bug, fixed-in-master
