### ISSUE TITLE
Invalid Syntax when installing with pip (khal version 0.8.4)

### ISSUE THREAD

**Issue by allo-** [pimutils/khal#527] opened 2016-11-16 18:10 UTC
pip Output:

	$ pip install khal
	[... some already satisfied dependencies ...]
	Installing collected packages: khal, click, icalendar, vdirsyncer, configobj, tzlocal, click-threading, requests-toolbelt, click-log, atomicwrites
	  Running setup.py install for khal
		  File "/usr/local/lib/python2.7/dist-packages/khal/ui/widgets.py", line 383
			def __init__(self, *args, EditWidget=ExtendedEdit, validate=False, **kwargs):
											   ^
		SyntaxError: invalid syntax
		
		
		Installing ikhal script to /usr/local/bin
		Installing khal script to /usr/local/bin
	  Could not find .egg-info directory in install record for khal
	  Running setup.py install for click
		
		warning: no previously-included files matching '*.pyc' found under directory 'docs'
		warning: no previously-included files matching '*.pyo' found under directory 'docs'
		warning: no previously-included files matching '*.pyc' found under directory 'tests'
		warning: no previously-included files matching '*.pyo' found under directory 'tests'
		warning: no previously-included files matching '*.pyc' found under directory 'examples'
		warning: no previously-included files matching '*.pyo' found under directory 'examples'
		no previously-included directories found matching 'docs/_build'
	  Could not find .egg-info directory in install record for click>=3.2 (from khal)
	  Running setup.py install for icalendar
		
		warning: no previously-included files matching '*.pyc' found under directory 'src/icalendar'
		warning: no previously-included files matching '*~' found under directory 'src/icalendar'
	  Could not find .egg-info directory in install record for icalendar (from khal)
	Compiling /tmp/pip-build-dAaiaj/vdirsyncer/vdirsyncer/cli/tasks.py ...
	  File "/tmp/pip-build-dAaiaj/vdirsyncer/vdirsyncer/cli/tasks.py", line 63
		nonlocal sync_failed
						   ^
	SyntaxError: invalid syntax

	Compiling /tmp/pip-build-dAaiaj/vdirsyncer/vdirsyncer/storage/base.py ...
	  File "/tmp/pip-build-dAaiaj/vdirsyncer/vdirsyncer/storage/base.py", line 27
		class Storage(metaclass=StorageMeta):
							   ^
	SyntaxError: invalid syntax

	  Running setup.py install for configobj
		
	  Could not find .egg-info directory in install record for configobj (from khal)
	  Running setup.py install for tzlocal
		
	  Could not find .egg-info directory in install record for tzlocal>=1.0 (from khal)
	Successfully installed khal click icalendar vdirsyncer configobj tzlocal click-threading requests-toolbelt click-log atomicwrites
	Cleaning up...

**Comment by geier** [comment] 2016-11-16 20:10
From version 0.8 khal does not support python 2 any more, either use python 3 or khal 0.7.x, the former method is obviously recommended. 

I thought we wouldt abort and print a warning if one is trying to install with python 2. I'll investigate.

**Comment by allo-** [comment] 2016-11-16 21:09
Ah, okay. I thought pip would automatically decide if it uses python or python3 ...

**Comment by untitaker** [comment] 2016-12-15 10:30
I'm closing this since it's not a bug.

**Closed by untitaker** 2016-12-15 10:30 UTC

**Comment by geier** [comment] 2016-12-15 13:24
@untitaker do you know if/how we can make pip (under python 2) not even try to install the package?

**Comment by untitaker** [comment] 2016-12-15 13:37
You can raise an exception in `setup.py` if you're not running under Python 3.

**Comment by geier** [comment] 2016-12-15 13:47
I thought we had that already, but it wasn't working somehow. Turns
out we do and it works as intended, but not on the 0.8.x branch.


Quoting Markus Unterwaditzer (2016-12-15 14:37:55)
