### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by guerra13** [pimutils/khal#870] opened 2019-05-30 18:58 UTC
The command line khal doesn't allow deleting an event.

Please, make it possible to instruct ikhal to save events by pressing a key, rather than by quitting the application.

**Comment by d7415** [comment] 2019-08-31 20:46
> The command line khal doesn't allow deleting an event.

`khal edit` handles this.

> Please, make it possible to instruct ikhal to save events by pressing a key, rather than by quitting the application.

Duplicate of #866.

**Closed** 2019-09-11 21:00 UTC
Labels: type: duplicate
