### ISSUE TITLE
Use gnu parse_datetime for entering dates/times

### ISSUE THREAD

**Issue by bernhardbrunner** [pimutils/khal#443] opened 2016-06-14 16:31 UTC
I would propose to use gnu parse_datetime for entering times, which allows 'natural' language input like "friday +2 weeks". There is a python module with name parsedatetime, but I don't know if it is as powerful as the gnu version, which is used in the linux date command.

**Comment by untitaker** [comment] 2016-06-14 16:56
This is a duplicate of #169, which I think already suggests the same thing in the OP.

**Closed by untitaker** 2016-06-14 16:56 UTC

**Comment by bernhardbrunner** [comment] 2016-06-14 17:03
Ah, ok. So you closed the first entry without notice or reply.

On 2016-06-14 18:56, Markus Unterwaditzer wrote:
> This is a duplicate of #169
> <https://github.com/pimutils/khal/issues/169>, which I think already
> suggests the same thing in the OP.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pimutils/khal/issues/443#issuecomment-225945916>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AAY6oNH5X7m92PaqnHoOfrzWdNDWvUGDks5qLt1KgaJpZM4I1g5Z>.
>


-- 
bernhard.brunner@epr.ch

**Comment by untitaker** [comment] 2016-06-14 17:09
No, #169 is still open (which was opened earlier).

**Comment by untitaker** [comment] 2016-06-14 17:10
Oh I see that you also opened https://github.com/pimutils/khal/issues/442 -- we did close that issue, but *with* reply.

**Comment by bernhardbrunner** [comment] 2016-06-14 17:13
Yeah, when I checked back my entry was gone, so I thought it had gotten 
lost and reposted. nvm, I see that the idea is already in the works. 
Really a great program, exactly what is was looking for. Cheers, and 
have a good one.

On 2016-06-14 19:10, Markus Unterwaditzer wrote:
> Oh I see that you also opened #442
> <https://github.com/pimutils/khal/issues/442> -- we did close that
> issue, but /with/ reply.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pimutils/khal/issues/443#issuecomment-225949702>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AAY6oAOIQAjzoe2kXJUNJkBLBKGDORjVks5qLuCCgaJpZM4I1g5Z>.
>


-- 
bernhard.brunner@epr.ch
