### ISSUE TITLE
KeyError on files with RECURRENCE-ID but no "master"

### ISSUE THREAD

**Issue by JKatzwinkel** [pimutils/khal#323] opened 2016-01-10 14:42 UTC
Only on certain events, `khal` crashes like this:

		Traceback (most recent call last):
			File "/usr/bin/khal", line 9, in <module>
				load_entry_point('khal==0.7.1.dev41+ng699b6c3.d20160108', 'console_scripts', 'khal')()
			File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
				return self.main(*args, **kwargs)
			File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
				rv = self.invoke(ctx)
			File "/usr/lib/python3.5/site-packages/click/core.py", line 1037, in invoke
				return Command.invoke(self, ctx)
			File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
				return ctx.invoke(self.callback, **ctx.params)
			File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
				return callback(*args, **kwargs)
			File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
				return f(get_current_context(), *args, **kwargs)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/cli.py", line 227, in cli
				ctx.invoke(cli.commands[command])
			File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
				return callback(*args, **kwargs)
			File "/usr/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
				return f(get_current_context(), *args, **kwargs)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/cli.py", line 255, in calendar
				full=full
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/controllers.py", line 148, in calendar
				locale=locale)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/calendar_display.py", line 184, in vertical_month
				multiple, color, highlight_event_days, locale)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/calendar_display.py", line 128, in str_week
				devents = list(collection.get_events_on(day))
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/khalendar/khalendar.py", line 317, in <genexpr>
				return (self._cover_event(event) for event in events)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/khalendar/backend.py", line 433, in get_floating
				yield self.construct_event(item, href, start, end, ref, etag, calendar, dtype)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/khalendar/backend.py", line 515, in construct_event
				ref=ref,
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/khalendar/event.py", line 143, in fromString
				return cls.fromVEvents(events, ref, **kwargs)
			File "/usr/lib/python3.5/site-packages/khal-0.7.1.dev41+ng699b6c3.d20160108-py3.5.egg/khal/khalendar/event.py", line 136, in fromVEvents
				instcls = cls._get_type_from_vDDD(vevents[ref]['DTSTART'])
		KeyError: '1451779200'

This happens only occasionally and only on google calendars synced with vdirsyncer.
The timestamp causing the KeyError represents Jan 3rd at 1 AM. On this date, said google calendar contains an all-day event which recurs daily for about a week, but it seems like it is only the occurence on Jan 3rd causing this problem. In its `.ics` file, the event looks like this:

    BEGIN:VEVENT
    DTSTART;VALUE=DATE:20160103
    DTEND;VALUE=DATE:20160104
    DTSTAMP:20160108T175109Z
    UID:7[...]@google.com
    RECURRENCE-ID;VALUE=DATE:20160103
    CREATED:20151216T103115Z
    DESCRIPTION:
    LAST-MODIFIED:20160102T142954Z
    LOCATION:
    SEQUENCE:1
    STATUS:CONFIRMED
    SUMMARY: [...]
    TRANSP:TRANSPARENT
    [...]
    END:VEVENT

In my sqlite database, where the contents of `vevents` come from, all rows usually seem to have `PROTO` stored in their `ref` column. There is only one single row where this is not the case:

    sqlite> select * from recs_float where ref is not 'PROTO';
    1451779200|1451865600|dde22800042d40ed9566e83b7f0b70ea.ics|1451779200|1451779200|0|cranio

I couldn't get into why this event has its `DTSTART` timestamp or whatever in its `ref` row, nor could I find any difference between the event I suspect to be the cause of this and other all-day-events that seem ok.

**Comment by geier** [comment] 2016-01-11 11:22
I'll look into this. Thank you for reporting!

**Comment by geier** [comment] 2016-01-11 11:22
also: are there no additional VEVENTS in that file with the same UID?

**Comment by JKatzwinkel** [comment] 2016-01-11 14:34
No, this file contains only one VEVENT. It has been synced from google cal by `vdirsyncer 0.7.5-1`. None of the `.ics` files belonging to that calendar contain more than one VEVENT. The event that has its timestamp in the `ref` column in `recs_float` is an all-day event which actually belongs to one single event spanning multiple days.

**Comment by geier** [comment] 2016-01-11 22:51
Ok, the problem is, that there really *should* be another VEVENT with the same UID and without a RECURRENCE-ID property in there. How did you create that .ics file?

**Comment by JKatzwinkel** [comment] 2016-01-12 00:18
I retrieved the calendar's 'private address' under its 'Calendar Settings' at the `calendar.google.com` web interface. This is a URI pointing at an `.ics` file. This I put into my `vdirsyncer` config file under a `[storage]` section of type `http`, corresponding to a local storage of type `filesystem` with its `fileextension = .ics`. Those two are synced by `vdirsyncer sync`. This has worked before, I have been viewing (as this is a read-only solution obviously) a different google calendar in
`khal` for weeks.

When `grep`ing for `BEGIN:VEVENT` in the local storage directory, I get exactly as many results as files in that directory. So I'm guessing none of those contain more than one `VEVENT`.

Sorry for bothering you with this mystery. I know that google calendars aren't really supposed to be used with vdirsyncer.

**Comment by geier** [comment] 2016-01-12 15:53
I'll give this a try with google myself and see if something can be done about that.

We can ofcourse work around this in khal, but probably should issue a warning (because all the other recurring events from that event will be missing).

**Comment by geier** [comment] 2016-03-06 21:09
also see #348 and #351 for the more examples of the same issue.

**Comment by untitaker** [comment] 2016-03-18 18:40
I'm not sure if there's a bug in vdirsyncer or khal.

Currently vdirsyncer puts every VEVENT component into its own file (regardless of reccurrence), perhaps that is the real issue?

**Comment by geier** [comment] 2016-03-18 18:59
@untitaker I believe all VEVENTS with the same UID should go into one .ics file, otherwise we would need to reed all .ics files first and than search through them by UID (because we need to add events with the same UID in order).

**Comment by untitaker** [comment] 2016-03-18 19:09
@geier I'm on it. I strongly agree, it's just not a case I thought of.

**Comment by geier** [comment] 2016-03-18 19:17
there is so much stuff about icalendars I never dreamed to think of before it broke...

**Comment by untitaker** [comment] 2016-03-18 19:37
Please take a look at https://github.com/pimutils/vdirsyncer/pull/391

After this fix has landed in vdirsyncer, two synchronizations should fix all items.

However, I'd like @JKatzwinkel to try the patch before releasing.

**Comment by geier** [comment] 2016-03-18 19:44
@josswright @benv666 if you are up to it, you might want to try out pimutils/vdirsyncer#391 as well and see if those issues are gone.

**Comment by untitaker** [comment] 2016-03-22 20:01
I've released 0.9.3 which contains the fix. @JKatzwinkel just upgrading vdirsyncer to that version and syncing twice should fix everything.

**Comment by JKatzwinkel** [comment] 2016-03-31 23:06
Sorry I missed your mention. Will look into that, thanks!

**Comment by josswright** [comment] 2016-04-12 07:57
Just had a look at this, and it does seem to have solved the problem.

**Comment by untitaker** [comment] 2016-04-12 16:31
@josswright Could you try deleting khal's database?

**Comment by josswright** [comment] 2016-04-12 20:07
Just to see if I might be able to break it? :)

I just moved khal.db to khal.db.old and ran khal again. No problems at all.

Just as an extra data point here, the reason that I came back and tried this is that khal was crashing with this issue for an event in today's calendar. That event is now no longer causing problems.

**Comment by untitaker** [comment] 2016-04-12 20:44
@josswright `khal.db` is merely a cache, removing it should clean up any remainders of the broken events.

Glad to hear it works now!

**Comment by geier** [comment] 2016-04-12 21:49
While I'm wondering why khal didn't pick up the changed ics files I'm glad the issues is resolved.

**Closed by geier** 2016-04-12 21:49 UTC
Labels: bug, in progress, needs info

**Comment by JKatzwinkel** [comment] 2016-04-12 21:56
Totally fixed. Thanks a lot!
