### ISSUE TITLE
Add a delete function

### ISSUE THREAD

**Issue by varac** [pimutils/khal#667] opened 2017-06-08 19:22 UTC
Please add a feature to delete events.

**Comment by hobarrera** [comment] 2017-06-08 19:40
Huh, I just realized that `ikhal` has this, but `khal` does not. The hard part is: how to uniquely identify a single event from the cli.

**Comment by varac** [comment] 2017-06-08 21:18
Indeed. How about using the UID - it's long, but it's handy because it's the same on the server as well (working with vdirsyncer I'm used to UIDs).

**Comment by geier** [comment] 2017-06-08 22:35
You can use the `edit` command to delete events. 

Am 8. Juni 2017 23:18:11 MESZ schrieb varac <notifications@github.com>:
>Indeed. How about using the UID - it's long, but it's handy because
>it's the same on the server as well (working with vdirsyncer I'm used
>to UIDs).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/khal/issues/667#issuecomment-307230275

-- 
Sent from my phone. Please excuse my brevity.

**Comment by geier** [comment] 2017-06-13 18:05
this is actually a duplicate of #603

**Closed by geier** 2017-06-13 18:05 UTC
Labels: type: enhancement
