### ISSUE TITLE
khal crashes 🔥

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#608] opened 2017-03-22 23:15 UTC
```
$ khal
critical: Cannot understand event 2233f40b-9d80-49ff-aac0-01c2f957fc9f.ics from calendar shiftgig,
critical:  you might want tofile an issue at https://github.com/pimutils/khal/issues
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.4.dev26+ng93e6861', 'console_scripts', 'khal')()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 250, in cli
    ctx.invoke(cli.commands[command])
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/cli.py", line 289, in calendar
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 105, in calendar
    env=env,
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 264, in khal_list
    width=width,
  File "/usr/lib/python3.6/site-packages/khal/controllers.py", line 182, in get_events_between
    events = sorted(collection.get_localized(start_local, end_local))
  File "/usr/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 148, in <genexpr>
    return (self._cover_event(event) for event in events)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/backend.py", line 485, in get_localized
    yield self.construct_event(item, href, start, end, ref, etag, calendar, dtype)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/backend.py", line 564, in construct_event
    ref=ref,
  File "/usr/lib/python3.6/site-packages/khal/khalendar/event.py", line 155, in fromString
    return cls.fromVEvents(events, ref, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/event.py", line 149, in fromVEvents
    return instcls(vevents, ref=ref, **kwargs)
  File "/usr/lib/python3.6/site-packages/khal/khalendar/event.py", line 634, in __init__
    starttz = getattr(self._vevents[self.ref]['DTSTART'].dt, 'tzinfo', None)
KeyError: '1490803200'
```

Here's the event, generated by Google/FastMail (fastmail proxies this for me):

```icalendar
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//FastMail/1.0/EN
BEGIN:VTIMEZONE
TZID:America/Chicago
BEGIN:STANDARD
DTSTART:19700101T000000
RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T000000
RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=ACCEPTED:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=ACCEPTED:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED HAS SPACE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=ACCEPTED:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=hbarrera@shiftgig.com;PARTSTAT=ACCEPTED:MAILTO:
 hbarrera@shiftgig.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=ACCEPTED:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED HAS SPACE;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=ACCEPTED:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=REDACTED@REDACTED.com;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:
 REDACTED@REDACTED.com
ATTENDEE;CN=6. Innovation;PARTSTAT=ACCEPTED:MAILTO:
 shiftgig.com_2d3731353633323230363033@resource.calendar.google.com
CREATED:20161116T180332Z
DTEND;TZID=America/Chicago:20170329T162500
DTSTAMP:20170322T171834Z
DTSTART;TZID=America/Chicago:20170329T160000
LOCATION:6. Innovation
ORGANIZER;CN=P/E/D Planning and other Open Meetings:MAILTO:
 shiftgig.com_os0igdci9i3rj8c9a5kh5k79jc@group.calendar.google.com
RECURRENCE-ID:20170329T160000
SEQUENCE:2
SUMMARY:Infrastructure Planning
TRANSP:OPAQUE
UID:406336i-tuh758kcpv6o53qb9ng7371sh4@google.com
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:'Infrastructure Planning' starts in 10 minutes
TRIGGER:-PT10M
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by geier** [comment] 2017-03-22 23:58
This is a duplicate of #447.

The issue here is that the ics contains a VEVENT with a recurrence-id but no master/proto event.

**Comment by hobarrera** [comment] 2017-03-23 02:20
> This is a duplicate of #447.

Sorry!

> The issue here is that the ics contains a VEVENT with a recurrence-id but no master/proto event.

Is this wrong as per the RFC? I'm only attending a single event, of the recurring series (which is on a shared calendar), so only the instance I'm attending to was generated for my personal calendar.

**Comment by geier** [comment] 2017-03-23 09:54
No worries, no this is explicitly allowed, it's just not clear yet how
to handle some variants, your example would be easy.

Quoting Hugo Osvaldo Barrera (2017-03-23 03:20:10)

**Comment by geier** [comment] 2017-03-23 10:09
but I'll try to take care of at least the easy cases (like yours) ASAP (and won't import all other ones, so it doesn't crash), I'll reopen for that.

**Comment by geier** [comment] 2017-03-23 10:10
bug for the crash (which would be fixed with not importing those events any more) and enhancement for actually dealing with those VEVENTS properly.

**Closed** 2017-06-12 07:11 UTC
Labels: pri:High, type: bug, type: enhancement
