### ISSUE TITLE
Khal crashes on search with KeyError: 'PROTO'

### ISSUE THREAD

**Issue by varac** [pimutils/khal#681] opened 2017-06-23 09:13 UTC
Khal works fine so far for me, but I cannot search for most patterns (although some pattern work weirdly):

```
--- ~ » khal -v search e
debug: khal 0.9.5
debug: using the config file at /home/varac/.config/khal/config
debug: Using config:
debug: [default]
debug:   default_calendar: default
debug:   default_command: calendar
debug:   show_all_days: False
debug:   print_new: False
debug:   highlight_event_days: False
debug:   timedelta: 2 days, 0:00:00
debug: [calendars]
debug:   [[default]]
debug:     path: /home/varac/.vdirsyncer/provider/calendars/personal
debug:     color: light green
debug:     readonly: False
debug:     type: calendar
debug:   [[aaa]]
debug:     path: /home/varac/.vdirsyncer/provider/calendars/aaa
debug:     color: dark green
debug:     readonly: False
debug:     type: calendar
debug:   [[bbb]]
debug:     path: /home/varac/.vdirsyncer/bbb/calendars/mwealtonah_shared_by_bbb.altonah
debug:     color: 
debug:     readonly: False
debug:     type: calendar
debug:   [[ccc]]
debug:     path: /home/varac/.vdirsyncer/ccc/calendars/personal_shared_by_ccc
debug:     color: 
debug:     readonly: False
debug:     type: calendar
debug: [sqlite]
debug:   path: /home/varac/.local/share/khal/khal.db
debug: [locale]
debug:   firstweekday: 0
debug:   unicode_symbols: True
debug:   default_timezone: Europe/Berlin
debug:   local_timezone: Europe/Berlin
debug:   timeformat: %H:%M
debug:   dateformat: %d.%m.
debug:   longdateformat: %d.%m.%Y
debug:   datetimeformat: %d.%m. %H:%M
debug:   longdatetimeformat: %d.%m.%Y %H:%M
debug:   weeknumbers: False
debug: [keybindings]
debug:   up: ['up', 'k']
debug:   down: ['down', 'j']
debug:   right: ['right', 'l', ' ']
debug:   left: ['left', 'h', 'backspace']
debug:   new: ['n']
debug:   delete: ['d']
debug:   view: ['enter']
debug:   external_edit: ['meta E']
debug:   today: ['t']
debug:   save: ['meta enter']
debug:   duplicate: ['p']
debug:   export: ['e']
debug:   mark: ['v']
debug:   other: ['o']
debug:   search: ['/']
debug:   quit: ['q', 'Q']
debug: [view]
debug:   dynamic_days: True
debug:   event_view_weighting: 1
debug:   event_view_always_visible: False
debug:   theme: dark
debug:   frame: False
debug:   bold_for_light_color: True
debug:   agenda_event_format: {calendar-color}{cancelled}{start-end-time-style} {title}{repeat-symbol}{description-separator}{description}{reset}
debug:   agenda_day_format: {bold}{name}, {date-long}{reset}
debug:   event_format: {calendar-color}{cancelled}{start}-{end} {title}{repeat-symbol}{description-separator}{description}{reset}
debug: [highlight_days]
debug:   method: fg
debug:   color: 
debug:   multiple: 
debug:   default_color: 
debug: created version table
debug: tables for calendar aaa exist
debug: tables for calendar default exist
debug: tables for calendar bbb exist
debug: tables for calendar ccc exist
Traceback (most recent call last):
  File "/home/varac/.local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/cli.py", line 536, in search
    events = sorted(collection.search(search_string))
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/khalendar/khalendar.py", line 316, in <genexpr>
    return (self._cover_event(event) for event in self._backend.search(search_string))
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/khalendar/backend.py", line 574, in search
    event = self.get(href, calendar=calendar)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/khalendar/backend.py", line 550, in get
    ref=ref,
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/khalendar/event.py", line 155, in fromString
    return cls.fromVEvents(events, ref, **kwargs)
  File "/home/varac/.local/venvs/khal/lib/python3.5/site-packages/khal/khalendar/event.py", line 148, in fromVEvents
    instcls = cls._get_type_from_vDDD(vevents[ref]['DTSTART'])
KeyError: 'PROTO'

--- ~ » khal search sava
23.06. 15:00-23.06. 16:00 Sava
```

**Comment by geier** [comment] 2017-06-27 12:13
Thank you for reporting this, I'll close this as a duplicate of #677 though.

**Closed by geier** 2017-06-27 12:13 UTC
