### ISSUE TITLE
offset in synced calendar

### ISSUE THREAD

**Issue by mokas01** [pimutils/khal#731] opened 2017-10-14 16:57 UTC
Hi,

I have an issue with [this](https://pastebin.aquilenet.fr/?bb1b3b17725056d7#iyBcrFWyAtElDwKi/8TNcUHahAXYeLaUMX9pz6dCkGA=) and some other events from an online calendar : 2 hours offset.
This is an issue i don't have with other calandar clients (ical, Gnome Calendar), 

This is the locale part of my configuration

[locale]
local_timezone= Europe/Paris
timeformat= %H:%M
dateformat= %d.%m.
longdateformat= %d.%m.%Y
datetimeformat= %d.%m. %H:%M
longdatetimeformat= %d.%m.%Y %H:%M
weeknumbers = left

**Comment by geier** [comment] 2017-10-16 13:18
At what time is that event starting for you? For me, khal shows it starting at 6:00 and the DTSTART in that .ics confirms that it should start at 6:00.

```
19.10. 06:00-19.10. 07:00 xxxxxxxxxxxxxxxxxx changed but irrelevant xxxxxxxxxxxxxxx
```

**Comment by mokas01** [comment] 2017-10-17 11:43
It should actually be at 9.00. Sorry for the error, there is a 3 hours offset. For example, the same event, taken of the same online calendar, is at 9.00 in Gnome calendar

**Comment by geier** [comment] 2017-10-17 16:34
I am very sure that 6:00 is in fact the correct start time for that event (see the DTSTART property between BEGIN:VEVENT and END:VEVENT: ``DTSTART:20171019T060000``, with no timezone information present, so it should start at 6:00 at no matter what timezone you are in).

BUT, I could reproduce your problem:
while I couldn't get gnome-calendar to import that .ics file and it looks like it can't be done [0, 1], gnome-calendar uses the same backend as evolution, so I imported that event with evolution. In evolution that events starts at 6:00 as it should. Gnome-calendar also shows the event now, but starting at 8:00.

I conclude that this is a serious error in gnome-calendar and **I can only recommend not to use gnome-calendar on Ubuntu 16.04** (and perhaps also not on other platforms/versions).

I am using gnome-calendar in version 3.20.4-0ubuntu0.1 in evolution in 3.18.5.2-0ubuntu3.2 on Ubuntu 16.04.3 LTS.

[0] https://askubuntu.com/questions/805664/gnome-does-not-load-ics-calendar-file
[1] I also feel that gnome-calendar took minimalism one or two steps too far

**Comment by geier** [comment] 2017-10-17 16:42
That bug is reported for ubuntu here https://bugs.launchpad.net/ubuntu/+source/gnome-calendar/+bug/1573581 (and still open since more than a year).

**Comment by geier** [comment] 2017-10-17 16:47
and here for gnome-calendar https://bugzilla.gnome.org/show_bug.cgi?id=764963 and
https://bugzilla.gnome.org/show_bug.cgi?id=786155

Now I don't feel so bad about the occasional bug in khal any more :smiling_imp:

**Comment by geier** [comment] 2017-10-17 16:47
I'll close this as this isn't an issue with khal.

**Closed** 2017-10-18 07:27 UTC
