### ISSUE TITLE
Using displayname doesn't ignore the newline character

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [pimutils/khal#765] opened 2018-03-26 16:56 UTC
I am using a calendar of type `discover` and it uses the `displayname` file to display the name of the calendars. However, if that file happens to end by a newline, a few things happens:

* It is no longer possible to set a default calendar (you get `critical: in section [default] DisplayName1 is not valid for 'default_calendar', must be one of ['DisplayName1\n', 'DisplayName2\n']`).
* The "pop-up" to change the calendar of an event in interactive mode has gaps.

I believe having a newline at the end of the `displayname` isn't a problem and thus should be ignored by khal. Some text editors don't even allow to remove it.

I am able to make a PR to fix this, I just need to know if it's okay to modifiy this behaviour.

**Comment by geier** [comment] 2022-07-11 21:57
I believe we fixed this some time ago by accident. At least I can't reproduce this with recent version of khal.

**Comment by geier** [comment] 2022-07-11 21:58
Looks like it was fixed by #979

**Closed by geier** 2022-07-11 21:58 UTC
Labels: type: bug
