### ISSUE TITLE
Offset problem in ikhal

### ISSUE THREAD

**Issue by kflak** [pimutils/khal#684] opened 2017-07-06 19:10 UTC
Hi, 
When opening ikhal I'm getting a very large list of errors that run something like this:

Unknown exception happened.
Traceback (most recent call last):
  File "/usr/local/Cellar/khal/0.9.6/libexec/lib/python3.6/site-packages/khal/khalendar/khalendar.py", line 303, in _update_vevent
    update(event.raw, href=href, etag=etag, calendar=calendar)
  File "/usr/local/Cellar/khal/0.9.6/libexec/lib/python3.6/site-packages/khal/khalendar/backend.py", line 249, in update
    ical = icalendar.Event.from_ical(vevent_str)
  File "/usr/local/Cellar/khal/0.9.6/libexec/lib/python3.6/site-packages/icalendar/cal.py", line 383, in from_ical
    vals = factory(factory.from_ical(vals))
  File "/usr/local/Cellar/khal/0.9.6/libexec/lib/python3.6/site-packages/icalendar/prop.py", line 836, in from_ical
    'Offset must be less than 24 hours, was %s' % ical)
ValueError: Offset must be less than 24 hours, was +5020
warning: Skipping Work/M2CD-9-1-FE5A7A40-E229-4297-B4A6-AA207BAE03E2.ics: Offset must be less than 24 hours, was +5020
warning: This event will not be available in khal.

The calendar events all come from icloud via vdirsyncer, mac OS Sierra, ikhal version 0.9.6

**Comment by geier** [comment] 2017-07-19 12:29
This is a duplicate of #140, which is an [icalendar](https://github.com/collective/icaledar) problem and which I try to fix there https://github.com/collective/icalendar/pull/235, but in the meantime you can install [this branch of icalendar](https://github.com/geier/icalendar/tree/ignore_timezones_greater_24h).

**Closed by geier** 2017-07-19 12:29 UTC
