### ISSUE TITLE
Is possible to refresh running khal in interactive mode?

### ISSUE THREAD

**Issue by petr-fischer** [pimutils/khal#726] opened 2017-10-11 18:07 UTC
Is possible to refresh running khal in interactive mode to reload calendars from files?
What about scheduled (configurable timeout) auto-refresh?

**Comment by geier** [comment] 2017-10-12 15:06
Khal refreshes itself every 60s, manual refresh isn't supported at the moment. We have an issue for something similar already, so I'll close this as a duplicate of #536, but feel free to add to the discussion here or there.

**Closed by geier** 2017-10-12 15:06 UTC
