### ISSUE TITLE
Birthdays are shown for the day after

### ISSUE THREAD

**Issue by hobarrera** [pimutils/khal#296] opened 2015-11-11 19:26 UTC
When listing events for today (running simply `khal`), an entry for a contact's birthday that was yesterday is listed today.
I'm UTC-0300, so I'm guessing that maybe the event is spans from midnight-to-midnight UTC, hence, spills over into my next day.

**Comment by geier** [comment] 2015-11-11 19:36
Thanks for reporting this, I really should look into this. As it looks like this is a duplicate of #244 I'll close this as a duplicate.

**Comment by geier** [comment] 2015-11-18 23:28
@hobarrera Could you have a look at your db file and see what VEVENT is created?
Also: how does it look in ikhal?

I really cannot reproduce this, event when setting default and locale timezone to Buenos Aires :(

**Comment by hobarrera** [comment] 2015-11-19 15:43
Oh ikhal, the birthday appears on the correct day.
I do recall seeing the birthday for "today" on 2015-11-09 (about twenty minutes past midnight), and it being on 2015-11-08.

```
hugo@athena:~                                                                                                                   
$ khal at 2015-11-08
2015-11-08: REDACTED's birthday
Repeat: FREQ=YEARLY

hugo@athena:~                                                                                                                   
$ khal at 2015-11-09
2015-11-08: REDACTED's birthday
Repeat: FREQ=YEARLY
```

**Comment by hobarrera** [comment] 2015-11-19 15:45
```
$ echo .dump | sqlite3 khal.db | grep -B 1 -A 5 REDACTED
INSERT INTO "events" VALUES('9GLZ0DQP7V.vcf','birthdays',NULL,'1434270662.135381222','BEGIN:VEVENT
SUMMARY:REDACTED''s birthday
DTSTART;VALUE=DATE:19881108
DTEND;VALUE=DATE:19881109
UID:9GLZ0DQP7V.vcf
RRULE:FREQ=YEARLY
END:VEVENT
```

**Comment by geier** [comment] 2015-11-24 21:04
hmmm. Could you also grep for the href ('9GLZ0DQP7V.vcf')? Thank you!

**Comment by hobarrera** [comment] 2015-11-30 18:29
```
INSERT INTO "events" VALUES('9GLZ0DQP7V.vcf','birthdays',NULL,'1434270662.135381222','BEGIN:VEVENT
UID:9GLZ0DQP7V.vcf
INSERT INTO "recs_float" VALUES(594950400,595036800,'9GLZ0DQP7V.vcf','594950400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(626486400,626572800,'9GLZ0DQP7V.vcf','626486400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(658022400,658108800,'9GLZ0DQP7V.vcf','658022400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(689558400,689644800,'9GLZ0DQP7V.vcf','689558400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(721180800,721267200,'9GLZ0DQP7V.vcf','721180800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(752716800,752803200,'9GLZ0DQP7V.vcf','752716800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(784252800,784339200,'9GLZ0DQP7V.vcf','784252800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(815788800,815875200,'9GLZ0DQP7V.vcf','815788800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(847411200,847497600,'9GLZ0DQP7V.vcf','847411200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(878947200,879033600,'9GLZ0DQP7V.vcf','878947200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(910483200,910569600,'9GLZ0DQP7V.vcf','910483200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(942019200,942105600,'9GLZ0DQP7V.vcf','942019200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(973641600,973728000,'9GLZ0DQP7V.vcf','973641600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1005177600,1005264000,'9GLZ0DQP7V.vcf','1005177600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1036713600,1036800000,'9GLZ0DQP7V.vcf','1036713600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1068249600,1068336000,'9GLZ0DQP7V.vcf','1068249600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1099872000,1099958400,'9GLZ0DQP7V.vcf','1099872000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1131408000,1131494400,'9GLZ0DQP7V.vcf','1131408000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1162944000,1163030400,'9GLZ0DQP7V.vcf','1162944000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1194480000,1194566400,'9GLZ0DQP7V.vcf','1194480000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1226102400,1226188800,'9GLZ0DQP7V.vcf','1226102400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1257638400,1257724800,'9GLZ0DQP7V.vcf','1257638400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1289174400,1289260800,'9GLZ0DQP7V.vcf','1289174400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1320710400,1320796800,'9GLZ0DQP7V.vcf','1320710400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1352332800,1352419200,'9GLZ0DQP7V.vcf','1352332800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1383868800,1383955200,'9GLZ0DQP7V.vcf','1383868800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1415404800,1415491200,'9GLZ0DQP7V.vcf','1415404800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1446940800,1447027200,'9GLZ0DQP7V.vcf','1446940800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1478563200,1478649600,'9GLZ0DQP7V.vcf','1478563200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1510099200,1510185600,'9GLZ0DQP7V.vcf','1510099200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1541635200,1541721600,'9GLZ0DQP7V.vcf','1541635200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1573171200,1573257600,'9GLZ0DQP7V.vcf','1573171200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1604793600,1604880000,'9GLZ0DQP7V.vcf','1604793600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1636329600,1636416000,'9GLZ0DQP7V.vcf','1636329600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1667865600,1667952000,'9GLZ0DQP7V.vcf','1667865600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1699401600,1699488000,'9GLZ0DQP7V.vcf','1699401600','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1731024000,1731110400,'9GLZ0DQP7V.vcf','1731024000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1762560000,1762646400,'9GLZ0DQP7V.vcf','1762560000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1794096000,1794182400,'9GLZ0DQP7V.vcf','1794096000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1825632000,1825718400,'9GLZ0DQP7V.vcf','1825632000','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1857254400,1857340800,'9GLZ0DQP7V.vcf','1857254400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1888790400,1888876800,'9GLZ0DQP7V.vcf','1888790400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1920326400,1920412800,'9GLZ0DQP7V.vcf','1920326400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1951862400,1951948800,'9GLZ0DQP7V.vcf','1951862400','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(1983484800,1983571200,'9GLZ0DQP7V.vcf','1983484800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(2015020800,2015107200,'9GLZ0DQP7V.vcf','2015020800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(2046556800,2046643200,'9GLZ0DQP7V.vcf','2046556800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(2078092800,2078179200,'9GLZ0DQP7V.vcf','2078092800','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(2109715200,2109801600,'9GLZ0DQP7V.vcf','2109715200','PROTO',0,'birthdays');
INSERT INTO "recs_float" VALUES(2141251200,2141337600,'9GLZ0DQP7V.vcf','2141251200','PROTO',0,'birthdays');
```

**Comment by hobarrera** [comment] 2015-11-30 18:32
Looks like this person's birthday is at 21:00 the day before.

Since I'm at UTC-0300, I'm guessing the birthday is set to be at midnight UTC, but then stored in my local timezone. Right?

This still doesn't quite explain why I see the birthday listed on the *following* day.

**Comment by geier** [comment] 2015-11-30 21:29
Especially as all those are from the `recs_float` table and the timestamps *should* be created with `datetime.datetime.utcfromtimestamp()` (but I'gm gonna triple check this again).

**Comment by geier** [comment] 2015-12-28 16:37
@hobarrera are you already using python 3.5?

**Comment by hobarrera** [comment] 2015-12-28 17:11
@geier, Yup, since 2015-09-15 (when it hit the Arch repos). Is this py35-specific?

**Comment by geier** [comment] 2015-12-28 17:16
Quoting Hugo Osvaldo Barrera (2015-12-28 18:11:16)
> @geier, Yup, since 2015-09-15 (when it hit the Arch repos). Is this py35-specific?

not sure, but there are some strange failures on travis with python 3.5
(branch refactor backend) that I cannot reproduce locally.

**Comment by hobarrera** [comment] 2015-12-28 17:17
You might want to install py35 (even if not as a default). I've found that having py{27,33,34,35} locally helps a lot with tests in general.

**Comment by geier** [comment] 2015-12-28 17:22
I've got them all and I neither using py35 in a virtualenv nor with tox I'm seeing those fails on my machine.

**Comment by hobarrera** [comment] 2015-12-28 17:32
I can't reproduce the `refactor_backend` travis failures with py35 either. Maybe they have something funky in their setup. :(

**Comment by geier** [comment] 2016-03-29 21:35
closed because nobody seems to have observed this issue since the backend has been rewritten.

**Closed by geier** 2016-03-29 21:35 UTC
Labels: bug
