### ISSUE TITLE
Khal (version 0.10.1) crashes with message "Cannot understand event"

### ISSUE THREAD

**Issue by tfinke** [pimutils/khal#923] opened 2020-03-12 11:25 UTC
Dear Maintainers, 

attached please find an ICS file which keeps khal crashing. 

It seems the problem is caused by a repeating event.

Best Regards

Torsten

[ae55af91f70151247d69fd4afbb3d6ee4f090b9e.txt](https://github.com/pimutils/khal/files/4323848/ae55af91f70151247d69fd4afbb3d6ee4f090b9e.txt)

**Comment by d7415** [comment] 2020-03-12 12:12
The problem is the timezone.

**Comment by d7415** [comment] 2020-03-12 12:26
It appears the problem is in `icalendar`, when parsing custom timezones. The error is actually raised in `dateutil` from an `RRULE` `UNTIL`.
> ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware

The `UNTIL`s do appear to be in UTC though.

From a glance at the RFC it looks like this is a valid ICS, but I'm unclear why it's not just using `Europe/Berlin` and feels the need to define its own.

**Comment by tfinke** [comment] 2020-03-12 14:15
the entry was created by the evolution program. I am afraid that it would be difficult to get it modifified. 

It would help a lot if khal would not crash and maybe ignore such entries.

**Comment by ephase** [comment] 2020-04-02 21:56
I could test with this repo https://github.com/simon-budig/icalendar/commit/c42e8220dd2911c8a0203cebb59e6c50370bf006 for iCalendar and khal work. The PR of @simon-budig is awaiting validation https://github.com/collective/icalendar/pull/304

It seems to reduce error on khal startup when populate sqlite db like in #905

**Comment by fkleon** [comment] 2020-08-24 04:03
I'm affected by this issue as well on khal 0.9.10 as packaged by Ubuntu 20.04.

The event causing this has also been generated by Evolution (and subsequently received by Thunderbird). ICS attached.

[d0843ef2a6e1f034772d1faac807a66e7ba35e26.txt](https://github.com/pimutils/khal/files/5115712/d0843ef2a6e1f034772d1faac807a66e7ba35e26.txt)

Stacktrace:
```
$ khal at 19/08/2020 11:30
Traceback (most recent call last):
  File "/usr/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.10', 'console_scripts', 'khal')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/khal/cli.py", line 608, in at
    rows = controllers.khal_list(
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 259, in khal_list
    current_events = get_events_between(
  File "/usr/lib/python3/dist-packages/khal/controllers.py", line 182, in get_events_between
    events = sorted(collection.get_localized(start_local, end_local))
  File "/usr/lib/python3/dist-packages/khal/khalendar/khalendar.py", line 148, in <genexpr>
    return (self._cover_event(event) for event in events)
  File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 482, in get_localized
    yield self.construct_event(item, href, start, end, ref, etag, calendar, dtype)
  File "/usr/lib/python3/dist-packages/khal/khalendar/backend.py", line 554, in construct_event
    return Event.fromString(item,
  File "/usr/lib/python3/dist-packages/khal/khalendar/event.py", line 151, in fromString
    calendar_collection = icalendar.Calendar.from_ical(event_str)
  File "/usr/lib/python3/dist-packages/icalendar/cal.py", line 369, in from_ical
    _timezone_cache[component['TZID']] = component.to_tz()
  File "/usr/lib/python3/dist-packages/icalendar/cal.py", line 610, in to_tz
    dst[tzname], component_transitions = self._extract_offsets(
  File "/usr/lib/python3/dist-packages/icalendar/cal.py", line 540, in _extract_offsets
    rrule = dateutil.rrule.rrulestr(rrulestr, dtstart=dtstart)
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1667, in __call__
    return self._parse_rfc(s, **kwargs)
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1548, in _parse_rfc
    return self._parse_rfc_rrule(lines[0], cache=cache,
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 1509, in _parse_rfc_rrule
    return rrule(dtstart=dtstart, cache=cache, **rrkwargs)
  File "/usr/lib/python3/dist-packages/dateutil/rrule.py", line 463, in __init__
    raise ValueError(
ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
```

**Comment by d7415** [comment] 2020-08-24 09:30
Thanks for testing. It looks like that PR might be stalled.

**Comment by d7415** [comment] 2020-08-24 13:40
The patch has been merged upstream, but not yet released.

**Comment by geier** [comment] 2022-05-06 17:25
Looks like there is a release now and I can import the event fine.

**Closed by geier** 2022-05-06 17:25 UTC
Labels: upstream
