### ISSUE TITLE
unsupported locale

### ISSUE THREAD

**Issue by rmad1717** [pimutils/khal#634] opened 2017-04-27 10:07 UTC
I have this issue on a Linux Mint 17.3 machine with python 3. 
```
Traceback (most recent call last):
  File "/usr/local/bin/khal", line 11, in <module>
    sys.exit(main_khal())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/cli.py", line 250, in cli
    ctx.invoke(cli.commands[command])
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/khal/cli.py", line 289, in calendar
    env={"calendars": ctx.obj['conf']['calendars']}
  File "/usr/local/lib/python3.5/dist-packages/khal/controllers.py", line 119, in calendar
    bold_for_light_color=bold_for_light_color)
  File "/usr/local/lib/python3.5/dist-packages/khal/calendar_display.py", line 170, in vertical_month
    weekheaders = get_weekheader(firstweekday)
  File "/usr/local/lib/python3.5/dist-packages/khal/calendar_display.py", line 41, in get_weekheader
    return _calendar.formatweekheader(2)
  File "/usr/lib/python3.5/calendar.py", line 301, in formatweekheader
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.5/calendar.py", line 301, in <genexpr>
    return ' '.join(self.formatweekday(i, width) for i in self.iterweekdays())
  File "/usr/lib/python3.5/calendar.py", line 515, in formatweekday
    with different_locale(self.locale):
  File "/usr/lib/python3.5/calendar.py", line 494, in __enter__
    _locale.setlocale(_locale.LC_TIME, self.locale)
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I found a simmilar issue but that was fixed earlier. Seems like this has cropped up again.

**Comment by untitaker** [comment] 2017-04-27 10:43
Well, what is your locale? Could you give me the output of `locale`?

**Comment by rmad1717** [comment] 2017-04-27 10:52
```
LANGUAGE=en_IN:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=
```

**Comment by geier** [comment] 2017-04-29 18:27
please try executing the below python script and report if it throws any errors on your system:

``` python
import calendar

_calendar = calendar.LocaleTextCalendar(0,  locale='en_IN')
print(_calendar.formatweekheader(2))
```

**Comment by geier** [comment] 2017-06-20 12:27
bump

**Comment by schaden-freude** [comment] 2017-08-11 19:28
I too have the problem.

Mo Tu We Th Fr Sa Su is the output of the script. No errors.

**Comment by geier** [comment] 2017-08-28 17:06
@schaden-freude, did you try it with your locale settings? (the output of `locale`)

**Comment by schaden-freude** [comment] 2017-08-28 18:54
I'm sorry I don't understand the question.

**Comment by geier** [comment] 2017-08-28 18:58
I could have been clearer: I was really wondering if you ran the above script as is, or replaced `en_IN` with your locally (if it isn't en_IN). You can get your locally by executing `locale` in a terminal. I believe we are using the LC_TIME locale settings, but if you use several different locale for different LC settings, please try all of them.

**Comment by schaden-freude** [comment] 2017-08-29 08:12
I ran the above script as is. My locale was en_IN. 

Anyway, I later set `LANG="en_US.utf8"` in my bashrc and now that the locale is en_US, khal works without throwing any errors.

**Comment by geier** [comment] 2017-09-05 19:01
My problem with this issue is, that I cannot reproduce it at all, even if I set an invalid locale, I get an error at a completely different part:

```
Traceback (most recent call last):
  File "/home/cg/.virtualenvs/khal/bin/khal", line 11, in <module>
    load_entry_point('khal==0.9.7.dev40+ng0e1d8de', 'console_scripts', 'khal')()
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/khal/cli.py", line 31, in <module>
    from . import __version__, controllers, khalendar
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/khal/controllers.py", line 33, in <module>
    from khal import (__productname__, __version__, calendar_display,
  File "/home/cg/.virtualenvs/khal/lib/python3.5/site-packages/khal/calendar_display.py", line 31, in <module>
    setlocale(LC_ALL, '')
  File "/home/cg/.virtualenvs/khal/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by oliverlorenz** [comment] 2018-01-23 14:32
I could solve the problem with this hint. https://github.com/turicas/rows/issues/260#issuecomment-339423321

I have no clue why this is working, but maybe it will help for your research

**Comment by untitaker** [comment] 2018-01-23 14:35
I think we can close this issue. This is always due to bad locale settings which is not a bug in khal

**Comment by geier** [comment] 2018-02-06 21:54
@untitaker agreed.

**Closed by geier** 2018-02-06 21:54 UTC
Labels: cannot reproduce, type: bug
