### ISSUE TITLE
0.9.10: test failure in test_description_and_location_and_categories

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/khal#825] opened 2018-12-01 16:41 UTC
On NetBSD/amd64 with python 3.7.1 I see:

````
================================================================= FAILURES ==================================================================
_______________________________________________ test_description_and_location_and_categories ________________________________________________

    def test_description_and_location_and_categories():
        for data_list, vevent in test_set_description_and_location_and_categories:
            with freeze_time('2014-02-16 12:00:00'):
                event = _construct_event(data_list.split(),
                                         description='please describe the event',
                                         location='in the office',
                                         categories='boring meeting',
                                         locale=LOCALE_BERLIN)
>               assert _replace_uid(event).to_ical() == vevent
E               AssertionError: assert b'BEGIN:VEVEN...ND:VEVENT\r\n' == b'BEGIN:VEVENT...ND:VEVENT\r\n'
E                 At index 253 diff: 44 != 111
E                 Left contains more items, first extra item: 10
E                 Use -v to get the full diff

tests/utils_test.py:569: AssertionError
======================================== 1 failed, 272 passed, 1 xfailed, 1 xpassed in 7.53 seconds =========================================
*** Error code 1
````
Let me know if you need more information. Thanks!

**Comment by lfam** [comment] 2018-12-04 00:02
Same issue on Guix with Python 3.7.0. I can also offer more info or run debug patches, etc.

**Comment by jonassmedegaard** [comment] 2018-12-13 14:32
Running the test with `-vv` seems to indicate that the generated code wrongly treats each character as a category, not as intended the whole string.

Likely related to https://github.com/collective/icalendar/pull/265

This fixes the test - but I am unaware if other places in code is wrong:

```patch
--- a/tests/utils_test.py
+++ b/tests/utils_test.py
@@ -564,7 +564,7 @@
             event = _construct_event(data_list.split(),
                                      description='please describe the event',
                                      location='in the office',
-                                     categories='boring meeting',
+                                     categories=['boring meeting'],
                                      locale=LOCALE_BERLIN)
             assert _replace_uid(event).to_ical() == vevent
 
```

**Comment by geier** [comment] 2019-03-25 13:33
Should be fixed with https://github.com/pimutils/khal/pull/850 , I'll try to get a release out ASAP.

**Closed by geier** 2019-03-25 13:33 UTC
